### ISSUE TITLE
allows arbitrary execution of any code

### ISSUE THREAD

**Issue by DanielFGray** [Tennu/tennu-eval#3]
`client.config('password')` shows bot's password in plaintext for chat to see, any user with !eval (which is by default all users) can run this, or use `client.quit()` to kill the bot.

even worse, this gives users the ability to modify the hosts' filesystem, since any user can `require('fs')` and execute commands for it

**Comment by VictorioBerra** [comment]
I will edit the README. This plugin is designed to be used with the "admin-commands" config option in the plugin tennu-admin https://github.com/Tennu/tennu-admin
